development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://lpqkeqbxphovyi:1560c46502907cf6f04a9cfb79b11cb5cab68fbd7ec8cc513151e8621f8e103a@ec2-54-83-50-145.compute-1.amazonaws.com:5432/d1ngi084n279lg
  channel_prefix: myapp_production
